import type { Config } from "tailwindcss";

// CSS custom properties in design-system/tokens.css are the source of truth.
// color-mix gives every semantic color working Tailwind slash-opacity support.
const tokenColor = (variable: string): string =>
  `color-mix(in srgb, var(${variable}) calc(<alpha-value> * 100%), transparent)`;

// Tailwind is the design system's structural/utility API, not a second theme.
const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        surface: tokenColor("--color-surface"),
        "surface-elevated": tokenColor("--color-surface-elevated"),
        "surface-subtle": tokenColor("--color-surface-subtle"),
        "surface-stroke": tokenColor("--color-surface-stroke"),
        overlay: tokenColor("--color-surface-overlay"),
        "media-overlay": tokenColor("--color-media-overlay"),
        "media-overlay-strong": tokenColor("--color-media-overlay-strong"),
        primary: tokenColor("--color-primary"),
        "primary-hover": tokenColor("--color-primary-hover"),
        accent: tokenColor("--color-accent"),
        "on-accent": tokenColor("--color-text-on-accent"),
        "on-media": tokenColor("--color-text-on-media"),
        "text-primary": tokenColor("--color-text-primary"),
        "text-secondary": tokenColor("--color-text-secondary"),
        "text-muted": tokenColor("--color-text-muted"),
        "text-disabled": tokenColor("--color-text-disabled"),
        "text-inverse": tokenColor("--color-text-inverse"),
        "border-subtle": tokenColor("--color-border-subtle"),
        "border-strong": tokenColor("--color-border-strong"),
        hover: tokenColor("--color-hover-fill"),
        pressed: tokenColor("--color-pressed-fill"),
        selection: tokenColor("--color-selection-fill"),
        "selection-stroke": tokenColor("--color-selection-stroke"),
        focus: tokenColor("--color-focus-ring"),
        "accent-surface": tokenColor("--color-accent-surface"),
        info: tokenColor("--color-info"),
        success: tokenColor("--color-success"),
        warning: tokenColor("--color-warning"),
        danger: tokenColor("--color-danger"),
        "info-subtle": tokenColor("--color-info-subtle"),
        "success-subtle": tokenColor("--color-success-subtle"),
        "warning-subtle": tokenColor("--color-warning-subtle"),
        "danger-subtle": tokenColor("--color-danger-subtle"),
        "role-assistant": tokenColor("--color-role-assistant"),
        "role-user": tokenColor("--color-role-user"),
        "role-thinking": tokenColor("--color-role-thinking"),
        "role-tool": tokenColor("--color-role-tool"),
        "role-status": tokenColor("--color-role-status"),
        "diff-added": tokenColor("--color-diff-added"),
        "diff-removed": tokenColor("--color-diff-removed"),
        "diff-added-subtle": tokenColor("--color-diff-added-subtle"),
        "diff-removed-subtle": tokenColor("--color-diff-removed-subtle"),
        "source-builtin": tokenColor("--color-source-builtin"),
        "source-library": tokenColor("--color-source-library"),
        "source-project": tokenColor("--color-source-project"),
        "source-project-subtle": tokenColor("--color-source-project-subtle"),
        "source-project-stroke": tokenColor("--color-source-project-stroke"),
        "source-global": tokenColor("--color-source-global"),
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        mono: ["var(--font-mono)"],
        pixel: ["var(--font-pixel)"],
      },
      fontSize: {
        overline: ["var(--text-overline)", { lineHeight: "var(--leading-overline)" }],
        micro: ["var(--text-micro)", { lineHeight: "var(--leading-micro)" }],
        detail: ["var(--text-detail)", { lineHeight: "var(--leading-detail)" }],
        caption: ["var(--text-caption)", { lineHeight: "var(--leading-caption)" }],
        label: ["var(--text-label)", { lineHeight: "var(--leading-label)" }],
        body: ["var(--text-body)", { lineHeight: "var(--leading-body)" }],
        title: ["var(--text-title)", { lineHeight: "var(--leading-title)" }],
        heading: ["var(--text-heading)", { lineHeight: "var(--leading-heading)" }],
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        icon: "var(--radius-icon)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        "3xl": "var(--radius-3xl)",
        capsule: "var(--radius-pill)",
      },
      spacing: {
        gutter: "var(--space-gutter)",
        section: "var(--space-section)",
        card: "var(--space-card)",
        row: "var(--space-row)",
        "control-gap": "var(--space-control-gap)",
        "control-sm": "var(--size-control-sm)",
        "control-md": "var(--size-control-md)",
        "control-lg": "var(--size-control-lg)",
        titlebar: "var(--size-titlebar)",
        "section-hero": "var(--size-section-hero)",
        sheet: "var(--space-sheet)",
      },
      maxWidth: {
        sheet: "var(--size-sheet)",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        capsule: "var(--shadow-capsule)",
        keycap: "var(--shadow-keycap)",
        elevated: "var(--shadow-elevated)",
        modal: "var(--shadow-modal)",
      },
      zIndex: {
        base: "var(--layer-base)",
        sticky: "var(--layer-sticky)",
        popover: "var(--layer-popover)",
        modal: "var(--layer-modal)",
        toast: "var(--layer-toast)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        slow: "var(--duration-slow)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
        spring: "var(--ease-spring)",
      },
      opacity: {
        6: "0.06",
        8: "0.08",
        35: "0.35",
        45: "0.45",
        55: "0.55",
        disabled: "var(--opacity-disabled)",
      },
      animation: {
        "indeterminate-bar": "indeterminate-bar 1.15s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
